# node: 该配置文件仅用于开发环境
server:
  context-path: /fcoin
  port: 8080
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
  undertow:
    io-threads: 2
    worker-threads: 5
    accesslog:
      enabled: true
      pattern: "%h %l %u %{time,[dd/MMM/yyyy:HH:mm:ss.SSS Z]} \"%r\" %s %b \"%{i,Referer}\" \"%{i,User-Agent}\""
      dir: "/var/fcoin/access-logs/fcoin"